version: "3.4"

services:
  streaming_app_dev:
    hostname: streaming_app_dev
    container_name: streaming_app_dev
    build:
      context: ./
      dockerfile: Dockerfile_dev
    volumes: 
      - ./app:/app
    ports:
      - 4200
    stdin_open: true

  streaming_app:
    hostname: streaming_app
    container_name: streaming_app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4200

networks: 
  default:
    external:
      name: streaming_app_network