version: "3.4"

services:
  stream_app_dev:
    hostname: stream_app_dev
    container_name: stream_app_dev
    build:
      context: ./
      dockerfile: Dockerfile_dev
    volumes: 
      - ./app:/app
    ports:
      - 4200:4200
    stdin_open: true

  # stream_app:
  #   hostname: stream_app
  #   container_name: stream_app
  #   restart: always
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4200

networks: 
  default:
    external:
      name: stream_app_network