version: "3.4"

services:
  streaming_api_dev:
    hostname: streaming_api_dev
    container_name: streaming_api_dev
    build:
      context: ./streaming_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./streaming_api/app:/app
    ports:
      - 8080:8080
    stdin_open: true

  streaming_api:
    hostname: streaming_api
    container_name: streaming_api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8443

networks: 
  default:
    external:
      name: streaming_app_network