version: "3.4"

services:
  stream_api_dev:
    hostname: stream_api_dev
    container_name: stream_api_dev
    build:
      context: ./stream_api
      dockerfile: Dockerfile_dev
    volumes: 
      - ./stream_api/app:/app
    ports:
      - 8080:8080
    stdin_open: true

  stream_api:
    hostname: stream_api
    container_name: stream_api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8443

networks: 
  default:
    external:
      name: stream_app_network