export const Mangas = [
    { name: 'Assassination Classroom' },
    { name: 'Beelzebub' },
    { name: 'Black Clover' },
    { name: 'Bleach' },
    { name: 'Boruto' },
    { name: 'D Gray Man' },
    { name: 'Dr Stone' },
    { name: 'Dragon Ball Super' },
    { name: 'Fairy Tail' },
    { name: 'Gantz' },
    { name: 'Gintama' },
    { name: 'Hajime No Ippo' },
    { name: 'Hunter X Hunter' },
    { name: 'Magi' },
    { name: 'My Hero Academia' },
    { name: 'Naruto' },
    { name: 'Naruto Gaiden' },
    { name: 'One Piece' },
    { name: 'One Punch Man' },
    { name: 'Shingeki No Kyojin' },
    { name: 'Soul Eater' },
    { name: 'The Breaker New Waves' },
    { name: 'The Seven Deadly Sins' },
    { name: 'Tokyo Ghoul Re' },
    { name: 'Tokyo Shinobi Squad' },
    { name: 'Toriko' }
]